### ISSUE TITLE
Add Buttons to the Tinicraft Game Screen

### ISSUE THREAD

**Issue by ErickN13** [ZeroAlvein/Tinicraft-Minicraft-for-Android#1]
I'm having trouble playing this game, because there are no buttons on the screen during the game, so even if I know how to play without buttons, it would be cooler to add some buttons to the screen like,The Open Inventory Button,The Action Button to Place and Remove items from the floor,It's just that

**Comment by ZeroAlvein** [comment]
I do not have source code so i have no means to change it in any way
I simply republished it since there was no easy place i could find to download it
